type: group
fields:
  kirbyseositeobject:
    label: SEO
    type: object
    fields:
      kirbyseositetitle:
        label: benjaminhaeberli.kirby-seo.site.title
        type: text
        help: benjaminhaeberli.kirby-seo.site.title.help
        maxlength: 80
      kirbyseoimage:
        label: benjaminhaeberli.kirby-seo.image
        type: files
        search: true
        sortBy: filename asc
        help: benjaminhaeberli.kirby-seo.image.help
        limit: 5
      kirbyseotwittercreator:
        label: benjaminhaeberli.kirby-seo.twitter.creator
        type: text
        placeholder: '@example'
        maxlength: 16
      kirbyseotwitterurl:
        label: benjaminhaeberli.kirby-seo.twitter.site
        type: text
        placeholder: '@example'
        maxlength: 16
